checks:
    php:
        excluded_dependencies:
            - flipboxdigital/spark
build:
  environment:
    timezone: UTC
    php:
      version: 7.1
      ini:
        date.timezone: 'UTC'
        memory_limit: '-1'
  project_setup:
      before:
        - mysql -e "CREATE DATABASE craft3test CHARACTER SET = 'utf8' COLLATE = 'utf8_unicode_ci'"
    tests:
      override:
        -
          command: 'php codeception.php run unit --coverage --coverage-xml --coverage-html'
          coverage:
            file: 'tests/_output/coverage.xml'
            format: 'clover'